from __future__ import annotations

import os
import sqlite3
import time
from collections.abc import Iterable, Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path

from . import __app_name__, __version__
from .errors import IndexInvalidError, IndexNotFoundError, OperationCancelled
from .formatting import human_size
from .pathing import join_windows_path, normalize_for_match, normalize_windows_path
from .platform import is_windows
from .progress import CancellationToken, ProgressCallback, ProgressUpdate, report

SCHEMA_VERSION = "1"
SQLITE_INT64_MIN = -(2**63)
SQLITE_INT64_MAX = 2**63 - 1


@dataclass(frozen=True)
class Entry:
    frn: str
    parent_frn: str
    name: str
    path: str
    is_dir: bool
    size: int
    tree_size: int
    mtime_ns: int
    attributes: int
    usn: int

    @property
    def display_size(self) -> str:
        return human_size(self.tree_size if self.is_dir else self.size)


def clamp_sqlite_integer(value: int) -> int:
    value = int(value)
    if value < SQLITE_INT64_MIN:
        return SQLITE_INT64_MIN
    if value > SQLITE_INT64_MAX:
        return SQLITE_INT64_MAX
    return value


def clamp_sqlite_nonnegative_integer(value: int) -> int:
    value = int(value)
    if value <= 0:
        return 0
    if value > SQLITE_INT64_MAX:
        return SQLITE_INT64_MAX
    return value


def _entry_sql_values(entry: Entry) -> tuple[object, ...]:
    return (
        entry.frn,
        entry.parent_frn,
        entry.name,
        entry.path,
        normalize_for_match(entry.path),
        int(entry.is_dir),
        clamp_sqlite_nonnegative_integer(entry.size),
        clamp_sqlite_nonnegative_integer(entry.tree_size),
        clamp_sqlite_integer(entry.mtime_ns),
        clamp_sqlite_integer(entry.attributes),
        clamp_sqlite_integer(entry.usn),
    )


def connect(path: str, *, readonly: bool = False) -> sqlite3.Connection:
    if readonly:
        uri = Path(path).resolve(strict=False).as_uri() + "?mode=ro"
        conn = sqlite3.connect(uri, uri=True)
    else:
        conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    if not readonly:
        conn.execute("PRAGMA journal_mode = DELETE")
        conn.execute("PRAGMA synchronous = NORMAL")
    conn.execute("PRAGMA temp_store = MEMORY")
    conn.execute("PRAGMA cache_size = -131072")
    return conn


def create_schema(conn: sqlite3.Connection) -> None:
    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS metadata (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS entries (
            frn TEXT PRIMARY KEY,
            parent_frn TEXT NOT NULL,
            name TEXT NOT NULL,
            path TEXT NOT NULL UNIQUE,
            path_norm TEXT NOT NULL UNIQUE,
            is_dir INTEGER NOT NULL,
            size INTEGER NOT NULL,
            tree_size INTEGER NOT NULL,
            mtime_ns INTEGER NOT NULL,
            attributes INTEGER NOT NULL,
            usn INTEGER NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_entries_parent ON entries(parent_frn);
        CREATE INDEX IF NOT EXISTS idx_entries_path_norm ON entries(path_norm);
        CREATE INDEX IF NOT EXISTS idx_entries_tree_size ON entries(tree_size DESC);
        """
    )


def set_metadata(conn: sqlite3.Connection, **items: object) -> None:
    conn.executemany(
        "INSERT OR REPLACE INTO metadata(key, value) VALUES (?, ?)",
        [(key, str(value)) for key, value in items.items()],
    )


def get_metadata(conn: sqlite3.Connection) -> dict[str, str]:
    return {row["key"]: row["value"] for row in conn.execute("SELECT key, value FROM metadata")}


def validate_index(conn: sqlite3.Connection) -> dict[str, str]:
    meta = get_metadata(conn)
    required = {
        "app_name",
        "app_version",
        "schema_version",
        "volume_root",
        "volume_serial",
        "filesystem",
        "root_path",
        "root_frn",
        "journal_id",
        "indexed_usn",
    }
    missing = required - set(meta)
    if missing:
        raise IndexInvalidError(f"Index metadata is missing: {', '.join(sorted(missing))}.")
    if meta["app_name"] != __app_name__:
        raise IndexInvalidError(f"Index was generated by {meta['app_name']}, not {__app_name__}.")
    if meta["schema_version"] != SCHEMA_VERSION:
        raise IndexInvalidError(
            f"Index schema {meta['schema_version']} is not supported by schema {SCHEMA_VERSION}."
        )
    return meta


def require_index(path: str) -> None:
    if not os.path.exists(path):
        raise IndexNotFoundError(f"Index not found: {path}")


def row_to_entry(row: sqlite3.Row) -> Entry:
    return Entry(
        frn=row["frn"],
        parent_frn=row["parent_frn"],
        name=row["name"],
        path=row["path"],
        is_dir=bool(row["is_dir"]),
        size=int(row["size"]),
        tree_size=int(row["tree_size"]),
        mtime_ns=int(row["mtime_ns"]),
        attributes=int(row["attributes"]),
        usn=int(row["usn"]),
    )


def entry_by_frn(conn: sqlite3.Connection, frn: str) -> Entry | None:
    row = conn.execute("SELECT * FROM entries WHERE frn = ?", (frn,)).fetchone()
    return row_to_entry(row) if row else None


def entry_by_path(conn: sqlite3.Connection, path: str) -> Entry | None:
    row = conn.execute(
        "SELECT * FROM entries WHERE path_norm = ?",
        (normalize_for_match(path),),
    ).fetchone()
    return row_to_entry(row) if row else None


def upsert_entry(conn: sqlite3.Connection, entry: Entry) -> None:
    path_norm = normalize_for_match(entry.path)
    conflicting = conn.execute(
        "SELECT frn FROM entries WHERE path_norm = ? AND frn != ?",
        (path_norm, entry.frn),
    ).fetchone()
    if conflicting is not None:
        delete_subtree(conn, conflicting["frn"])
    conn.execute(
        """
        INSERT INTO entries (
            frn, parent_frn, name, path, path_norm, is_dir, size, tree_size,
            mtime_ns, attributes, usn
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(frn) DO UPDATE SET
            parent_frn = excluded.parent_frn,
            name = excluded.name,
            path = excluded.path,
            path_norm = excluded.path_norm,
            is_dir = excluded.is_dir,
            size = excluded.size,
            tree_size = excluded.tree_size,
            mtime_ns = excluded.mtime_ns,
            attributes = excluded.attributes,
            usn = excluded.usn
        """,
        _entry_sql_values(entry),
    )


def bulk_insert_entries(
    conn: sqlite3.Connection,
    entries: Iterable[Entry],
    *,
    chunk_size: int = 5000,
    progress: ProgressCallback | None = None,
    token: CancellationToken | None = None,
) -> int:
    sql = """
        INSERT OR IGNORE INTO entries (
            frn, parent_frn, name, path, path_norm, is_dir, size, tree_size,
            mtime_ns, attributes, usn
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """
    chunk: list[tuple[object, ...]] = []
    count = 0
    for entry in entries:
        if token is not None:
            token.check()
        chunk.append(_entry_sql_values(entry))
        if len(chunk) >= chunk_size:
            cursor = conn.executemany(sql, chunk)
            count += cursor.rowcount if cursor.rowcount >= 0 else len(chunk)
            report(progress, ProgressUpdate("write", count, None, f"Indexed {count:,} entries"))
            chunk.clear()
    if chunk:
        cursor = conn.executemany(sql, chunk)
        count += cursor.rowcount if cursor.rowcount >= 0 else len(chunk)
        report(progress, ProgressUpdate("write", count, None, f"Indexed {count:,} entries"))
    return count


def update_ancestor_sizes(conn: sqlite3.Connection, parent_frn: str, delta: int) -> None:
    if delta == 0:
        return
    current = parent_frn
    seen: set[str] = set()
    while current and current not in seen:
        seen.add(current)
        row = conn.execute(
            "SELECT parent_frn, tree_size FROM entries WHERE frn = ?",
            (current,),
        ).fetchone()
        if row is None:
            break
        tree_size = clamp_sqlite_nonnegative_integer(int(row["tree_size"]) + int(delta))
        conn.execute("UPDATE entries SET tree_size = ? WHERE frn = ?", (tree_size, current))
        next_parent = row["parent_frn"]
        if not next_parent or next_parent == current:
            break
        current = next_parent


def _path_depth(path: str) -> int:
    separator = "\\" if is_windows() else "/"
    stripped = normalize_windows_path(path).rstrip(separator)
    if not stripped:
        return 0
    return stripped.count(separator)


def recompute_tree_sizes(
    conn: sqlite3.Connection,
    *,
    progress: ProgressCallback | None = None,
    token: CancellationToken | None = None,
) -> None:
    rows = conn.execute("SELECT frn, parent_frn, is_dir, size, path FROM entries").fetchall()
    is_dir = {row["frn"]: bool(row["is_dir"]) for row in rows}
    parents = {row["frn"]: row["parent_frn"] for row in rows}
    sizes = {
        row["frn"]: 0 if bool(row["is_dir"]) else int(row["size"])
        for row in rows
    }

    ordered = sorted(rows, key=lambda row: _path_depth(row["path"]), reverse=True)
    for idx, row in enumerate(ordered, start=1):
        if token is not None:
            token.check()
        frn = row["frn"]
        parent_frn = parents.get(frn)
        if parent_frn and parent_frn != frn and is_dir.get(parent_frn, False):
            sizes[parent_frn] = sizes.get(parent_frn, 0) + sizes.get(frn, 0)
        if idx % 10000 == 0:
            report(
                progress,
                ProgressUpdate("size-recalc", idx, len(rows), f"Recalculated {idx:,} entries"),
            )

    conn.executemany(
        "UPDATE entries SET tree_size = ? WHERE frn = ?",
        [(clamp_sqlite_nonnegative_integer(tree_size), frn) for frn, tree_size in sizes.items()],
    )
    report(
        progress,
        ProgressUpdate("size-recalc", len(rows), len(rows), f"Recalculated {len(rows):,} entries"),
    )


def descendant_frns(conn: sqlite3.Connection, root_frn: str, *, include_root: bool = False) -> list[str]:
    rows = conn.execute(
        """
        WITH RECURSIVE subtree(frn) AS (
            SELECT frn FROM entries WHERE parent_frn = ? AND frn != ?
            UNION ALL
            SELECT e.frn FROM entries e JOIN subtree s ON e.parent_frn = s.frn
            WHERE e.frn != e.parent_frn
        )
        SELECT frn FROM subtree
        """,
        (root_frn, root_frn),
    ).fetchall()
    result = [row["frn"] for row in rows]
    if include_root:
        result.insert(0, root_frn)
    return result


def delete_subtree(conn: sqlite3.Connection, root_frn: str) -> Entry | None:
    root = entry_by_frn(conn, root_frn)
    if root is None:
        return None
    update_ancestor_sizes(conn, root.parent_frn, -root.tree_size)
    to_delete = descendant_frns(conn, root_frn, include_root=True)
    conn.executemany("DELETE FROM entries WHERE frn = ?", [(frn,) for frn in to_delete])
    return root


def refresh_descendant_paths(conn: sqlite3.Connection, root_frn: str) -> None:
    queue = [root_frn]
    while queue:
        parent = entry_by_frn(conn, queue.pop(0))
        if parent is None:
            continue
        child_rows = conn.execute(
            "SELECT frn, name FROM entries WHERE parent_frn = ? AND frn != ? ORDER BY name",
            (parent.frn, parent.frn),
        ).fetchall()
        for row in child_rows:
            path = join_windows_path(parent.path, row["name"])
            path_norm = normalize_for_match(path)
            conflicting = conn.execute(
                "SELECT frn FROM entries WHERE path_norm = ? AND frn != ?",
                (path_norm, row["frn"]),
            ).fetchone()
            if conflicting is not None:
                delete_subtree(conn, conflicting["frn"])
            conn.execute(
                "UPDATE entries SET path = ?, path_norm = ? WHERE frn = ?",
                (normalize_windows_path(path), path_norm, row["frn"]),
            )
            queue.append(row["frn"])


def count_entries(conn: sqlite3.Connection, where: str = "", params: tuple[object, ...] = ()) -> int:
    sql = "SELECT COUNT(*) AS count FROM entries"
    if where:
        sql += f" WHERE {where}"
    row = conn.execute(sql, params).fetchone()
    return int(row["count"])


@contextmanager
def cancellable_query(conn: sqlite3.Connection, token: CancellationToken | None) -> Iterator[None]:
    def handler() -> int:
        if token is not None and token.cancelled:
            return 1
        return 0

    conn.set_progress_handler(handler, 2000)
    try:
        yield
    except sqlite3.OperationalError as exc:
        if token is not None and token.cancelled:
            raise OperationCancelled("Operation cancelled.") from exc
        raise
    finally:
        conn.set_progress_handler(None, 0)


def stamp_finished_metadata(conn: sqlite3.Connection, indexed_usn: int) -> None:
    set_metadata(
        conn,
        app_name=__app_name__,
        app_version=__version__,
        schema_version=SCHEMA_VERSION,
        indexed_usn=indexed_usn,
        updated_at_ns=time.time_ns(),
    )
